name: Package and Publish to GitHub Packages Sample

#on: [push]
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore
        working-directory: DemoCoreServices/DemoCoreServices

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: DemoCoreServices/DemoCoreServices

      # タグのバージョンを取得
      - name: Get latest tag
        id: version
        run: |
          git fetch --tags
          ## 最新のタグを取得し、プレフィックスの 'v' を取り除く
          #LATEST_TAG=$(git tag --sort=-creatordate | head -n 1 | sed 's/^v//')
          # タグをセマンティックバージョン順にソートして最新のタグを取得
          LATEST_TAG=$(git tag | sort -V | tail -n 1 | sed 's/^v//')
          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found"
            exit 1
          else
            echo "Latest tag: $LATEST_TAG"
            echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          fi

      # NuGetパッケージを生成し、GitHub Packagesに公開
      - name: Package and publish to GitHub Packages
        run: |
          dotnet pack --configuration Release /p:PackageVersion=${{ env.LATEST_TAG }} --output ./artifacts
          dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        working-directory: ConsoleApp1/ConsoleApp1
